### ISSUE TITLE
Nothing is rendered after installing 

### ISSUE THREAD

**Issue by azheanda** [chrismbeckett/meteor-metro-ui2#2]
I tried to render a tile but It doesn't display a tile for me in the running app. Any suggestions?

**Comment by chrismbeckett** [comment]
Checkout the demos on the MetroUI site and compare the HTML markup with your own. I suspect you have the wrong HTML structure or are missing some CSS classes.

**Comment by azheanda** [comment]
Ah, got it. I guess I didn't get it when I saw "Make sure that you wrap your markup in an outer DIV tag with the appropriate class tag" in your usage description until I saw "5 simple steps to your style" on metroui.org.ua just now.
